name: yolobase
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
  - python=3.11
  - pip:
      - torch==2.2.2
      - torchvision==0.17.2
      - torchaudio
      - torch-summary
      - ultralytics
      - numpy==1.26.4
      - pyyaml==6.0.1
      - timm==1.0.14
      - albumentations==2.0.4
      - onnx==1.14.0
      - onnxruntime==1.16.1
      - opencv-python==4.9.0.80
      - pycocotools==2.0.7
      - psutil==5.9.8
      - huggingface-hub==0.23.2
      - py-cpuinfo==9.0.0
      - marshmallow
      - safetensors==0.4.3
      - matplotlib
      - scipy==1.13.0
      - supervision==0.22.0