name: mlbase
channels:
  - conda-forge
  - pytorch-nightly
  - apple
dependencies:
  - python=3.10
  - tensorflow-deps
  - pip:
      - torch
      - torchvision
      - torchaudio
      - torch-summary
      - numpy
      - marshmallow
      - tensorflow-macos==2.10
      - tensorflow-metal==0.6.0
      - tensorflow_datasets
      - keras_cv==0.3.5
      - safetensors
